### ISSUE TITLE
Slack user avatar not displaying

### ISSUE THREAD

**Issue by atvi-tmiller** [krauters/github-notifier#34]
slack user avatars are not showing correctly.  a brief google search suggests that `image_72` might not exist and to use other sizes if necessary

**Comment by coltenkrauter** [comment]
Thanks for bringing this up.

I will add some debugging and we'll get to the bottom of this.

Thank you for your Google search, I'll take a look at that. 

I also know that there's a possibility for username mismatches if for example a user used a different email address for their GitHub than their Slack account. 

We should be able to get a fix for either situation soon.

**Comment by coltenkrauter** [comment]
Is this issue with all user avatars? 

Or just some?

**Comment by coltenkrauter** [comment]
Per the [user.list](https://api.slack.com/methods/users.list), it looks like `image_72` will be present. But, just in case, I don't mind adding fallbacks in #35.

**Comment by coltenkrauter** [comment]
@atvi-tmiller 

Is this issue with all user avatars? Or just some? 

---

In the PR #35 (1.2.0) I just merged, I added some logging. If the issue continues to occur with version [1.2.0](https://buymeacoffee.com/coltenkrauter/releases/tag/1.2.0), then please check [the logs. ](https://github.com/krauters/github-notifier/blob/main/src/utils/slack/client.ts#L148-L156)

I expect that, for the user/s that are not seeing an avatar, there will be a log starting with this,

```
No user match found after checking against [
```

Can you share this log and the few subsequent logs? (redact names/emails)

**Comment by atvi-tmiller** [comment]
ah yeah, it's not finding the user
```
##[debug]Tried to match username [<redacted>] against Slack user.profile.email (contains), display_name and real_name fields
##[debug]Since no Slack user match found, unable to @mention user or use their profile image
```

oh, I think in our slack the `real_name` is all lowercase :)

**Comment by coltenkrauter** [comment]
Oh I see.. Okay, to possible solutions here. 

1) I just pushed #39.... Perhaps that will resolve it.

2) You can specify `user-mappings` in the action to correct for username mappings that cannot be reasonably determined automatically. 

```yaml
...
    - uses: krauters/github-notifier@main
      with:
        github-tokens: ${{ secrets.GH_TOKEN_GH_NOTIFIER }}, ${{ secrets.GH_TOKEN_GH_NOTIFIER_FOR_ANOTHER_ORG }}
        channels: C07L8EWB389
        slack-token: ${{ secrets.SLACK_TOKEN_GH_NOTIFIER }}
        user-mappings: GiHubUsername:slack-username
...
```
